### ISSUE TITLE
SacaleDepth

### ISSUE THREAD

**Issue by bhack** [RuijieZhu94/mmdepth#1]
Are you going to save the scaled metric depth with this model on inference?

**Comment by RuijieZhu94** [comment]
Sorry, I didn't quite understand what you meant. Our model directly predicts the metric depth during inference. Are you asking how to save relative depth maps?

**Comment by bhack** [comment]
it is related to `show` and `show-dir` args in the script in the case of the metric depth when we want to save the predicted depth on disk.

**Comment by RuijieZhu94** [comment]
Please use `out` arg to save the raw depth.
https://github.com/RuijieZhu94/mmdepth/blob/5d1efc730ac72911cf061154911f92d5f9959ad9/tools/test.py#L21

**Comment by bhack** [comment]
I will try but it seems that `projects.ScaleDepth.neck` is missing.

**Comment by RuijieZhu94** [comment]
Thanks for your reminder. In the initial version, we used `neck`, but it is not needed now. Just delete it in the configuration file.

**Comment by bhack** [comment]
OK, but It seems that that `mmdet` dependency  is restricting a lot the use of this on modern PyTorch versions. We need to go back to 2.1.x and cuda 11.8.

**Comment by bhack** [comment]
It seems there are some incompatibilities with numpy  2.x

**Comment by RuijieZhu94** [comment]
hi @bhack , thank you for your interest in my project. I provide [spec-list.txt](https://github.com/RuijieZhu94/mmdepth/blob/main/spec-list.txt) as a reference to reproduce the environment of my project. I have tested it on RTX3090 and Ubuntu 22.04 and it works fine. I hope it helps you.

**Comment by bhack** [comment]
What `requirements.txt` are needed just for testing inference? `runtime` ? `tests`?
 https://github.com/RuijieZhu94/mmdepth/blob/main/requirements.txt

**Comment by RuijieZhu94** [comment]
Yes, `runtime` & `tests`.

**Comment by RuijieZhu94** [comment]
Closing this issue. If there are any other questions please open another issue.
