### ISSUE TITLE
How to save the predicted results as npy?

### ISSUE THREAD

**Issue by chycxyzd** [RuijieZhu94/mmdepth#5]
I have successfully visualized the depth map through your 'inference.py', but I would like to view the specific measurement depth values and would like to save the predicted results as an .NPY file. Do you have any good methods to implement it?

**Comment by RuijieZhu94** [comment]
I usually multiply the data by 1000 and save it as a 16-bit raw PNG. If you want to save it as an .npy file, you may need to modify the relevant function at https://github.com/RuijieZhu94/mmdepth/blob/31089941abb70d15d8583f659acfa4dc0ee435a3/mmdepth/visualization/local_visualizer.py#L218

**Comment by chycxyzd** [comment]
Thank you for your reply. My issue has been resolved and I will close it.
