### ISSUE TITLE
How to use my own dataset to train

### ISSUE THREAD

**Issue by linjx0422** [RuijieZhu94/mmdepth#7]
Hello，thanks for your great work ！
Now, I have  a question : How to use my own dataset to train , it has differnet image size and crop method.what files and parameters shoud I modify?

Thanks again!

**Comment by RuijieZhu94** [comment]
Hi, @linjx0422, thank you for your attention! 

You might need to change the dataloader code https://github.com/RuijieZhu94/mmdepth/tree/main/mmdepth/datasets in and dataset config file in https://github.com/RuijieZhu94/mmdepth/blob/main/configs/_base_/datasets.

If you have further questions, please let me know:)

**Comment by linjx0422** [comment]
thanks for your reply！I will try！
