### ISSUE TITLE
Config file incomplete? 

### ISSUE THREAD

**Issue by Haiyan-Chris-Wang** [RuijieZhu94/mmdepth#8]
I couldn't find the model settings in the config file. It only contains the dataset setting?

**Comment by RuijieZhu94** [comment]
Hi @Haiyan-Chris-Wang, sorry for the late reply. I put the model config files into each project folder.

For example, you can find config file of our ScaleDepth in `projects/ScaleDepth/configs/ScaleDepth`.

**Comment by RuijieZhu94** [comment]
Closing this issue. If there are any other questions please open another issue.
